version: "3.7"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - "4444:4444"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: "unless-stopped"
    networks:
      - backend
networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
