version: "3.7"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: linebot-crypto
    ports:
      - "4325:4325"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    working_dir: /app
    restart: "unless-stopped"
networks:
  default:
    name: yadom
    external: true
volumes:
  dependencies:
    driver: local
