version: "3.7"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: linebot-crypto
    ports:
      - "4325:4325"
    volumes:
      - ./:/usr/src/app/linebot-crypto
      - dependencies:/usr/src/app/linebot-crypto/node_modules
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    working_dir: /usr/src/app/linebot-crypto
    restart: "unless-stopped"
    
    networks:
      - yadom

networks:
  yadom:
    external: true

volumes:
  dependencies:
    driver: local
