version: "3.7"

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: linebot-crypto
    ports:
      - "4325:4325"
    volumes:
      - ./:/usr/src/app/linebot-crypto
      - dependencies:/usr/src/app/linebot-crypto/node_modules
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    working_dir: /usr/src/app/linebot-crypto
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl -f http://localhost:4325/healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      start_period: 60s
    networks:
      - yadom

networks:
  yadom:
    driver: bridge

volumes:
  dependencies:
    driver: local
